#include <iostream>
using namespace std;
int main()
{
	long long int t,count;
    cin>>t;
    while(t-->0)
    {
    	long long int n;
    	cin>>n;
    	count=0;
    	while(n!=0)
    	{
    		if( (n%2048)==0)
			{
    			n=n-2048;
    			count++;
    		}
    		else
    		{
    			if((n%1024)==0)
    			{
    				n=n-1024;
    				count++;
				}
				else
				{
					if((n%512)==0)
					{
						n=n-512;
						count++;
					}
					else
					{
						if((n%256)==0)
						{
							n=n-256;
							count++;
						}
						else
						{
							if((n%128)==0)
							{
								n=n-128;
								count++;
							}
							else
							{
								if((n%64)==0)
								{
									n=n-64;
									count++;
						        }
						        else
						        {
						        	if((n%32)==0)
						        	{
						        		n=n-32;
						        		count++;
						        	}
						        	else
						        	{
						        		if((n%16)==0)
						        		{
						        			n=n-16;
						        			count++;
						        		}
						        		else
						        		{
						        			if((n%8)==0)
						        			{
						        				n=n-8;
						        				count++;
						                    }
						                    else
						                    {
						                    	if((n%4)==0)
						                    	{
						                    		n=n-4;
						                    		count++;
						                    	}
						                    	else
						                    	{
						                    		if((n%2)==0)
						                    		{
						                    			n=n-2;
						                    			count++;
						                    	    }
						                    	    else
						                    	    {
						                    	    	n=n-1;
						                    	    	count++;
													}
						                    	}
							                }
							            }
							        }
							    }
							}
						}
					}
				}
			}
		}
		cout<<count<<endl;	
	}
	
}
